### ISSUE TITLE
Useful links page

### ISSUE THREAD

**Issue by ioquatix** [ioquatix/programming.dojo.net.nz#29]
https://programming.dojo.net.nz/resources/useful-links

This page is a bit out of date. There are some interesting links, and others that 404 now.

I used to use it for my own links when I was teaching, I've already filtered out some of the junk, but more work is required.

Some ideas:

- Remove it entirely.
- Add link to cs unplugged
- Add link to other sites?

**Comment by courtneycb** [comment]
Resolved by #35
