### ISSUE TITLE
Contact page seems borked

### ISSUE THREAD

**Issue by ioquatix** [ioquatix/programming.dojo.net.nz#33]
https://programming.dojo.net.nz/welcome/contact-us/index

I don't even know if it's working.

**Comment by courtneycb** [comment]
We could remove this and point them to the issues page here (if they spot something wrong) and also supply an email address for general inquiries - instead of handling it through the site? Thoughts?

**Comment by ioquatix** [comment]
I think removing it and linking here is a great idea.

**Comment by ioquatix** [comment]
I don't think we need to supply an email address.

**Comment by courtneycb** [comment]
What about for purchasing posters? Do we still want them to come through the issue tracker? Or are we handling that another way now?

**Comment by ioquatix** [comment]
That never happened since the inception of the site. So maybe it doesn’t matter.
